default: &default
  host: localhost
  user: postgres
  password: root
  port: "5400"
  adapter: postgres

development:
  <<: *default
  db: todo_crystal

test:
  <<: *default
  db: todo_crystal_test

production:
  <<: *default
  db: todo_crystal_prod